/**
 * Autogenerated by Thrift Compiler (0.23.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.people.mreutegg.jsinfonia.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.23.0)", date = "2026-05-15")
public class TMemoryNodeInfo implements org.apache.thrift.TBase<TMemoryNodeInfo, TMemoryNodeInfo._Fields>, java.io.Serializable, Cloneable, Comparable<TMemoryNodeInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TMemoryNodeInfo");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField ADDRESS_SPACE_FIELD_DESC = new org.apache.thrift.protocol.TField("addressSpace", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField ITEM_SIZE_FIELD_DESC = new org.apache.thrift.protocol.TField("itemSize", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TMemoryNodeInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TMemoryNodeInfoTupleSchemeFactory();

  public int id; // required
  public int addressSpace; // required
  public int itemSize; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    ADDRESS_SPACE((short)2, "addressSpace"),
    ITEM_SIZE((short)3, "itemSize");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // ADDRESS_SPACE
          return ADDRESS_SPACE;
        case 3: // ITEM_SIZE
          return ITEM_SIZE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __ADDRESSSPACE_ISSET_ID = 1;
  private static final int __ITEMSIZE_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ADDRESS_SPACE, new org.apache.thrift.meta_data.FieldMetaData("addressSpace", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ITEM_SIZE, new org.apache.thrift.meta_data.FieldMetaData("itemSize", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TMemoryNodeInfo.class, metaDataMap);
  }

  public TMemoryNodeInfo() {
  }

  public TMemoryNodeInfo(
    int id,
    int addressSpace,
    int itemSize)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.addressSpace = addressSpace;
    setAddressSpaceIsSet(true);
    this.itemSize = itemSize;
    setItemSizeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TMemoryNodeInfo(TMemoryNodeInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    this.addressSpace = other.addressSpace;
    this.itemSize = other.itemSize;
  }

  @Override
  public TMemoryNodeInfo deepCopy() {
    return new TMemoryNodeInfo(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    setAddressSpaceIsSet(false);
    this.addressSpace = 0;
    setItemSizeIsSet(false);
    this.itemSize = 0;
  }

  public int getId() {
    return this.id;
  }

  public TMemoryNodeInfo setId(int id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public int getAddressSpace() {
    return this.addressSpace;
  }

  public TMemoryNodeInfo setAddressSpace(int addressSpace) {
    this.addressSpace = addressSpace;
    setAddressSpaceIsSet(true);
    return this;
  }

  public void unsetAddressSpace() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ADDRESSSPACE_ISSET_ID);
  }

  /** Returns true if field addressSpace is set (has been assigned a value) and false otherwise */
  public boolean isSetAddressSpace() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ADDRESSSPACE_ISSET_ID);
  }

  public void setAddressSpaceIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ADDRESSSPACE_ISSET_ID, value);
  }

  public int getItemSize() {
    return this.itemSize;
  }

  public TMemoryNodeInfo setItemSize(int itemSize) {
    this.itemSize = itemSize;
    setItemSizeIsSet(true);
    return this;
  }

  public void unsetItemSize() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ITEMSIZE_ISSET_ID);
  }

  /** Returns true if field itemSize is set (has been assigned a value) and false otherwise */
  public boolean isSetItemSize() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ITEMSIZE_ISSET_ID);
  }

  public void setItemSizeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ITEMSIZE_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.Integer)value);
      }
      break;

    case ADDRESS_SPACE:
      if (value == null) {
        unsetAddressSpace();
      } else {
        setAddressSpace((java.lang.Integer)value);
      }
      break;

    case ITEM_SIZE:
      if (value == null) {
        unsetItemSize();
      } else {
        setItemSize((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case ADDRESS_SPACE:
      return getAddressSpace();

    case ITEM_SIZE:
      return getItemSize();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case ADDRESS_SPACE:
      return isSetAddressSpace();
    case ITEM_SIZE:
      return isSetItemSize();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof TMemoryNodeInfo)
      return this.equals((TMemoryNodeInfo)that);
    return false;
  }

  public boolean equals(TMemoryNodeInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_addressSpace = true;
    boolean that_present_addressSpace = true;
    if (this_present_addressSpace || that_present_addressSpace) {
      if (!(this_present_addressSpace && that_present_addressSpace))
        return false;
      if (this.addressSpace != that.addressSpace)
        return false;
    }

    boolean this_present_itemSize = true;
    boolean that_present_itemSize = true;
    if (this_present_itemSize || that_present_itemSize) {
      if (!(this_present_itemSize && that_present_itemSize))
        return false;
      if (this.itemSize != that.itemSize)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + id;

    hashCode = hashCode * 8191 + addressSpace;

    hashCode = hashCode * 8191 + itemSize;

    return hashCode;
  }

  @Override
  public int compareTo(TMemoryNodeInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetId(), other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAddressSpace(), other.isSetAddressSpace());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAddressSpace()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.addressSpace, other.addressSpace);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetItemSize(), other.isSetItemSize());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetItemSize()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.itemSize, other.itemSize);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TMemoryNodeInfo(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("addressSpace:");
    sb.append(this.addressSpace);
    first = false;
    if (!first) sb.append(", ");
    sb.append("itemSize:");
    sb.append(this.itemSize);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TMemoryNodeInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TMemoryNodeInfoStandardScheme getScheme() {
      return new TMemoryNodeInfoStandardScheme();
    }
  }

  private static class TMemoryNodeInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<TMemoryNodeInfo> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, TMemoryNodeInfo struct) throws org.apache.thrift.TException {
      iprot.incrementRecursionDepth();
      try {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // ID
              if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                struct.id = iprot.readI32();
                struct.setIdIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // ADDRESS_SPACE
              if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                struct.addressSpace = iprot.readI32();
                struct.setAddressSpaceIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 3: // ITEM_SIZE
              if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                struct.itemSize = iprot.readI32();
                struct.setItemSizeIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      } finally {
        iprot.decrementRecursionDepth();
      }
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, TMemoryNodeInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI32(struct.id);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ADDRESS_SPACE_FIELD_DESC);
      oprot.writeI32(struct.addressSpace);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ITEM_SIZE_FIELD_DESC);
      oprot.writeI32(struct.itemSize);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TMemoryNodeInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TMemoryNodeInfoTupleScheme getScheme() {
      return new TMemoryNodeInfoTupleScheme();
    }
  }

  private static class TMemoryNodeInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<TMemoryNodeInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TMemoryNodeInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetAddressSpace()) {
        optionals.set(1);
      }
      if (struct.isSetItemSize()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetId()) {
        oprot.writeI32(struct.id);
      }
      if (struct.isSetAddressSpace()) {
        oprot.writeI32(struct.addressSpace);
      }
      if (struct.isSetItemSize()) {
        oprot.writeI32(struct.itemSize);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TMemoryNodeInfo struct) throws org.apache.thrift.TException {
      prot.incrementRecursionDepth();
      try {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(3);
        if (incoming.get(0)) {
          struct.id = iprot.readI32();
          struct.setIdIsSet(true);
        }
        if (incoming.get(1)) {
          struct.addressSpace = iprot.readI32();
          struct.setAddressSpaceIsSet(true);
        }
        if (incoming.get(2)) {
          struct.itemSize = iprot.readI32();
          struct.setItemSizeIsSet(true);
        }
      } finally {
        prot.decrementRecursionDepth();
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

