/**
 * Autogenerated by Thrift Compiler (0.23.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.people.mreutegg.jsinfonia.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.23.0)", date = "2026-05-15")
public class TMiniTransaction implements org.apache.thrift.TBase<TMiniTransaction, TMiniTransaction._Fields>, java.io.Serializable, Cloneable, Comparable<TMiniTransaction> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TMiniTransaction");

  private static final org.apache.thrift.protocol.TField TX_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("txId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField COMPARE_ITEMS_FIELD_DESC = new org.apache.thrift.protocol.TField("compareItems", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField READ_ITEMS_FIELD_DESC = new org.apache.thrift.protocol.TField("readItems", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField WRITE_ITEMS_FIELD_DESC = new org.apache.thrift.protocol.TField("writeItems", org.apache.thrift.protocol.TType.LIST, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TMiniTransactionStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TMiniTransactionTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String txId; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<TItem> compareItems; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<TItemReference> readItems; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<TItem> writeItems; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TX_ID((short)1, "txId"),
    COMPARE_ITEMS((short)2, "compareItems"),
    READ_ITEMS((short)3, "readItems"),
    WRITE_ITEMS((short)4, "writeItems");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TX_ID
          return TX_ID;
        case 2: // COMPARE_ITEMS
          return COMPARE_ITEMS;
        case 3: // READ_ITEMS
          return READ_ITEMS;
        case 4: // WRITE_ITEMS
          return WRITE_ITEMS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TX_ID, new org.apache.thrift.meta_data.FieldMetaData("txId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.COMPARE_ITEMS, new org.apache.thrift.meta_data.FieldMetaData("compareItems", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TItem.class))));
    tmpMap.put(_Fields.READ_ITEMS, new org.apache.thrift.meta_data.FieldMetaData("readItems", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TItemReference.class))));
    tmpMap.put(_Fields.WRITE_ITEMS, new org.apache.thrift.meta_data.FieldMetaData("writeItems", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TItem.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TMiniTransaction.class, metaDataMap);
  }

  public TMiniTransaction() {
  }

  public TMiniTransaction(
    java.lang.String txId,
    java.util.List<TItem> compareItems,
    java.util.List<TItemReference> readItems,
    java.util.List<TItem> writeItems)
  {
    this();
    this.txId = txId;
    this.compareItems = compareItems;
    this.readItems = readItems;
    this.writeItems = writeItems;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TMiniTransaction(TMiniTransaction other) {
    if (other.isSetTxId()) {
      this.txId = other.txId;
    }
    if (other.isSetCompareItems()) {
      java.util.List<TItem> __this__compareItems = new java.util.ArrayList<TItem>(other.compareItems.size());
      for (TItem other_element : other.compareItems) {
        __this__compareItems.add(new TItem(other_element));
      }
      this.compareItems = __this__compareItems;
    }
    if (other.isSetReadItems()) {
      java.util.List<TItemReference> __this__readItems = new java.util.ArrayList<TItemReference>(other.readItems.size());
      for (TItemReference other_element : other.readItems) {
        __this__readItems.add(new TItemReference(other_element));
      }
      this.readItems = __this__readItems;
    }
    if (other.isSetWriteItems()) {
      java.util.List<TItem> __this__writeItems = new java.util.ArrayList<TItem>(other.writeItems.size());
      for (TItem other_element : other.writeItems) {
        __this__writeItems.add(new TItem(other_element));
      }
      this.writeItems = __this__writeItems;
    }
  }

  @Override
  public TMiniTransaction deepCopy() {
    return new TMiniTransaction(this);
  }

  @Override
  public void clear() {
    this.txId = null;
    this.compareItems = null;
    this.readItems = null;
    this.writeItems = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getTxId() {
    return this.txId;
  }

  public TMiniTransaction setTxId(@org.apache.thrift.annotation.Nullable java.lang.String txId) {
    this.txId = txId;
    return this;
  }

  public void unsetTxId() {
    this.txId = null;
  }

  /** Returns true if field txId is set (has been assigned a value) and false otherwise */
  public boolean isSetTxId() {
    return this.txId != null;
  }

  public void setTxIdIsSet(boolean value) {
    if (!value) {
      this.txId = null;
    }
  }

  public int getCompareItemsSize() {
    return (this.compareItems == null) ? 0 : this.compareItems.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<TItem> getCompareItemsIterator() {
    return (this.compareItems == null) ? null : this.compareItems.iterator();
  }

  public void addToCompareItems(TItem elem) {
    if (this.compareItems == null) {
      this.compareItems = new java.util.ArrayList<TItem>();
    }
    this.compareItems.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<TItem> getCompareItems() {
    return this.compareItems;
  }

  public TMiniTransaction setCompareItems(@org.apache.thrift.annotation.Nullable java.util.List<TItem> compareItems) {
    this.compareItems = compareItems;
    return this;
  }

  public void unsetCompareItems() {
    this.compareItems = null;
  }

  /** Returns true if field compareItems is set (has been assigned a value) and false otherwise */
  public boolean isSetCompareItems() {
    return this.compareItems != null;
  }

  public void setCompareItemsIsSet(boolean value) {
    if (!value) {
      this.compareItems = null;
    }
  }

  public int getReadItemsSize() {
    return (this.readItems == null) ? 0 : this.readItems.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<TItemReference> getReadItemsIterator() {
    return (this.readItems == null) ? null : this.readItems.iterator();
  }

  public void addToReadItems(TItemReference elem) {
    if (this.readItems == null) {
      this.readItems = new java.util.ArrayList<TItemReference>();
    }
    this.readItems.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<TItemReference> getReadItems() {
    return this.readItems;
  }

  public TMiniTransaction setReadItems(@org.apache.thrift.annotation.Nullable java.util.List<TItemReference> readItems) {
    this.readItems = readItems;
    return this;
  }

  public void unsetReadItems() {
    this.readItems = null;
  }

  /** Returns true if field readItems is set (has been assigned a value) and false otherwise */
  public boolean isSetReadItems() {
    return this.readItems != null;
  }

  public void setReadItemsIsSet(boolean value) {
    if (!value) {
      this.readItems = null;
    }
  }

  public int getWriteItemsSize() {
    return (this.writeItems == null) ? 0 : this.writeItems.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<TItem> getWriteItemsIterator() {
    return (this.writeItems == null) ? null : this.writeItems.iterator();
  }

  public void addToWriteItems(TItem elem) {
    if (this.writeItems == null) {
      this.writeItems = new java.util.ArrayList<TItem>();
    }
    this.writeItems.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<TItem> getWriteItems() {
    return this.writeItems;
  }

  public TMiniTransaction setWriteItems(@org.apache.thrift.annotation.Nullable java.util.List<TItem> writeItems) {
    this.writeItems = writeItems;
    return this;
  }

  public void unsetWriteItems() {
    this.writeItems = null;
  }

  /** Returns true if field writeItems is set (has been assigned a value) and false otherwise */
  public boolean isSetWriteItems() {
    return this.writeItems != null;
  }

  public void setWriteItemsIsSet(boolean value) {
    if (!value) {
      this.writeItems = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case TX_ID:
      if (value == null) {
        unsetTxId();
      } else {
        setTxId((java.lang.String)value);
      }
      break;

    case COMPARE_ITEMS:
      if (value == null) {
        unsetCompareItems();
      } else {
        setCompareItems((java.util.List<TItem>)value);
      }
      break;

    case READ_ITEMS:
      if (value == null) {
        unsetReadItems();
      } else {
        setReadItems((java.util.List<TItemReference>)value);
      }
      break;

    case WRITE_ITEMS:
      if (value == null) {
        unsetWriteItems();
      } else {
        setWriteItems((java.util.List<TItem>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TX_ID:
      return getTxId();

    case COMPARE_ITEMS:
      return getCompareItems();

    case READ_ITEMS:
      return getReadItems();

    case WRITE_ITEMS:
      return getWriteItems();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TX_ID:
      return isSetTxId();
    case COMPARE_ITEMS:
      return isSetCompareItems();
    case READ_ITEMS:
      return isSetReadItems();
    case WRITE_ITEMS:
      return isSetWriteItems();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof TMiniTransaction)
      return this.equals((TMiniTransaction)that);
    return false;
  }

  public boolean equals(TMiniTransaction that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_txId = true && this.isSetTxId();
    boolean that_present_txId = true && that.isSetTxId();
    if (this_present_txId || that_present_txId) {
      if (!(this_present_txId && that_present_txId))
        return false;
      if (!this.txId.equals(that.txId))
        return false;
    }

    boolean this_present_compareItems = true && this.isSetCompareItems();
    boolean that_present_compareItems = true && that.isSetCompareItems();
    if (this_present_compareItems || that_present_compareItems) {
      if (!(this_present_compareItems && that_present_compareItems))
        return false;
      if (!this.compareItems.equals(that.compareItems))
        return false;
    }

    boolean this_present_readItems = true && this.isSetReadItems();
    boolean that_present_readItems = true && that.isSetReadItems();
    if (this_present_readItems || that_present_readItems) {
      if (!(this_present_readItems && that_present_readItems))
        return false;
      if (!this.readItems.equals(that.readItems))
        return false;
    }

    boolean this_present_writeItems = true && this.isSetWriteItems();
    boolean that_present_writeItems = true && that.isSetWriteItems();
    if (this_present_writeItems || that_present_writeItems) {
      if (!(this_present_writeItems && that_present_writeItems))
        return false;
      if (!this.writeItems.equals(that.writeItems))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetTxId()) ? 131071 : 524287);
    if (isSetTxId())
      hashCode = hashCode * 8191 + txId.hashCode();

    hashCode = hashCode * 8191 + ((isSetCompareItems()) ? 131071 : 524287);
    if (isSetCompareItems())
      hashCode = hashCode * 8191 + compareItems.hashCode();

    hashCode = hashCode * 8191 + ((isSetReadItems()) ? 131071 : 524287);
    if (isSetReadItems())
      hashCode = hashCode * 8191 + readItems.hashCode();

    hashCode = hashCode * 8191 + ((isSetWriteItems()) ? 131071 : 524287);
    if (isSetWriteItems())
      hashCode = hashCode * 8191 + writeItems.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TMiniTransaction other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetTxId(), other.isSetTxId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTxId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.txId, other.txId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCompareItems(), other.isSetCompareItems());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCompareItems()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.compareItems, other.compareItems);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetReadItems(), other.isSetReadItems());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReadItems()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.readItems, other.readItems);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetWriteItems(), other.isSetWriteItems());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWriteItems()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.writeItems, other.writeItems);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TMiniTransaction(");
    boolean first = true;

    sb.append("txId:");
    if (this.txId == null) {
      sb.append("null");
    } else {
      sb.append(this.txId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("compareItems:");
    if (this.compareItems == null) {
      sb.append("null");
    } else {
      sb.append(this.compareItems);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("readItems:");
    if (this.readItems == null) {
      sb.append("null");
    } else {
      sb.append(this.readItems);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("writeItems:");
    if (this.writeItems == null) {
      sb.append("null");
    } else {
      sb.append(this.writeItems);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TMiniTransactionStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TMiniTransactionStandardScheme getScheme() {
      return new TMiniTransactionStandardScheme();
    }
  }

  private static class TMiniTransactionStandardScheme extends org.apache.thrift.scheme.StandardScheme<TMiniTransaction> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, TMiniTransaction struct) throws org.apache.thrift.TException {
      iprot.incrementRecursionDepth();
      try {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // TX_ID
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.txId = iprot.readString();
                struct.setTxIdIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // COMPARE_ITEMS
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                  struct.compareItems = new java.util.ArrayList<TItem>(_list0.size);
                  @org.apache.thrift.annotation.Nullable TItem _elem1;
                  for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                  {
                    _elem1 = new TItem();
                    _elem1.read(iprot);
                    struct.compareItems.add(_elem1);
                  }
                  iprot.readListEnd();
                }
                struct.setCompareItemsIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 3: // READ_ITEMS
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list3 = iprot.readListBegin();
                  struct.readItems = new java.util.ArrayList<TItemReference>(_list3.size);
                  @org.apache.thrift.annotation.Nullable TItemReference _elem4;
                  for (int _i5 = 0; _i5 < _list3.size; ++_i5)
                  {
                    _elem4 = new TItemReference();
                    _elem4.read(iprot);
                    struct.readItems.add(_elem4);
                  }
                  iprot.readListEnd();
                }
                struct.setReadItemsIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 4: // WRITE_ITEMS
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list6 = iprot.readListBegin();
                  struct.writeItems = new java.util.ArrayList<TItem>(_list6.size);
                  @org.apache.thrift.annotation.Nullable TItem _elem7;
                  for (int _i8 = 0; _i8 < _list6.size; ++_i8)
                  {
                    _elem7 = new TItem();
                    _elem7.read(iprot);
                    struct.writeItems.add(_elem7);
                  }
                  iprot.readListEnd();
                }
                struct.setWriteItemsIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      } finally {
        iprot.decrementRecursionDepth();
      }
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, TMiniTransaction struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.txId != null) {
        oprot.writeFieldBegin(TX_ID_FIELD_DESC);
        oprot.writeString(struct.txId);
        oprot.writeFieldEnd();
      }
      if (struct.compareItems != null) {
        oprot.writeFieldBegin(COMPARE_ITEMS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.compareItems.size()));
          for (TItem _iter9 : struct.compareItems)
          {
            _iter9.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.readItems != null) {
        oprot.writeFieldBegin(READ_ITEMS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.readItems.size()));
          for (TItemReference _iter10 : struct.readItems)
          {
            _iter10.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.writeItems != null) {
        oprot.writeFieldBegin(WRITE_ITEMS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.writeItems.size()));
          for (TItem _iter11 : struct.writeItems)
          {
            _iter11.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TMiniTransactionTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TMiniTransactionTupleScheme getScheme() {
      return new TMiniTransactionTupleScheme();
    }
  }

  private static class TMiniTransactionTupleScheme extends org.apache.thrift.scheme.TupleScheme<TMiniTransaction> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TMiniTransaction struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetTxId()) {
        optionals.set(0);
      }
      if (struct.isSetCompareItems()) {
        optionals.set(1);
      }
      if (struct.isSetReadItems()) {
        optionals.set(2);
      }
      if (struct.isSetWriteItems()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetTxId()) {
        oprot.writeString(struct.txId);
      }
      if (struct.isSetCompareItems()) {
        {
          oprot.writeI32(struct.compareItems.size());
          for (TItem _iter12 : struct.compareItems)
          {
            _iter12.write(oprot);
          }
        }
      }
      if (struct.isSetReadItems()) {
        {
          oprot.writeI32(struct.readItems.size());
          for (TItemReference _iter13 : struct.readItems)
          {
            _iter13.write(oprot);
          }
        }
      }
      if (struct.isSetWriteItems()) {
        {
          oprot.writeI32(struct.writeItems.size());
          for (TItem _iter14 : struct.writeItems)
          {
            _iter14.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TMiniTransaction struct) throws org.apache.thrift.TException {
      prot.incrementRecursionDepth();
      try {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(4);
        if (incoming.get(0)) {
          struct.txId = iprot.readString();
          struct.setTxIdIsSet(true);
        }
        if (incoming.get(1)) {
          {
            org.apache.thrift.protocol.TList _list15 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
            struct.compareItems = new java.util.ArrayList<TItem>(_list15.size);
            @org.apache.thrift.annotation.Nullable TItem _elem16;
            for (int _i17 = 0; _i17 < _list15.size; ++_i17)
            {
              _elem16 = new TItem();
              _elem16.read(iprot);
              struct.compareItems.add(_elem16);
            }
          }
          struct.setCompareItemsIsSet(true);
        }
        if (incoming.get(2)) {
          {
            org.apache.thrift.protocol.TList _list18 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
            struct.readItems = new java.util.ArrayList<TItemReference>(_list18.size);
            @org.apache.thrift.annotation.Nullable TItemReference _elem19;
            for (int _i20 = 0; _i20 < _list18.size; ++_i20)
            {
              _elem19 = new TItemReference();
              _elem19.read(iprot);
              struct.readItems.add(_elem19);
            }
          }
          struct.setReadItemsIsSet(true);
        }
        if (incoming.get(3)) {
          {
            org.apache.thrift.protocol.TList _list21 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
            struct.writeItems = new java.util.ArrayList<TItem>(_list21.size);
            @org.apache.thrift.annotation.Nullable TItem _elem22;
            for (int _i23 = 0; _i23 < _list21.size; ++_i23)
            {
              _elem22 = new TItem();
              _elem22.read(iprot);
              struct.writeItems.add(_elem22);
            }
          }
          struct.setWriteItemsIsSet(true);
        }
      } finally {
        prot.decrementRecursionDepth();
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

