/**
 * Autogenerated by Thrift Compiler (0.23.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.people.mreutegg.jsinfonia.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.23.0)", date = "2026-05-15")
public class TResponse implements org.apache.thrift.TBase<TResponse, TResponse._Fields>, java.io.Serializable, Cloneable, Comparable<TResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TResponse");

  private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.BOOL, (short)1);
  private static final org.apache.thrift.protocol.TField READ_ITEMS_FIELD_DESC = new org.apache.thrift.protocol.TField("readItems", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField FAILED_COMPARES_FIELD_DESC = new org.apache.thrift.protocol.TField("failedCompares", org.apache.thrift.protocol.TType.LIST, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TResponseStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TResponseTupleSchemeFactory();

  public boolean success; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<TItem> readItems; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<TItemReference> failedCompares; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SUCCESS((short)1, "success"),
    READ_ITEMS((short)2, "readItems"),
    FAILED_COMPARES((short)3, "failedCompares");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SUCCESS
          return SUCCESS;
        case 2: // READ_ITEMS
          return READ_ITEMS;
        case 3: // FAILED_COMPARES
          return FAILED_COMPARES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SUCCESS_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.READ_ITEMS, new org.apache.thrift.meta_data.FieldMetaData("readItems", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TItem.class))));
    tmpMap.put(_Fields.FAILED_COMPARES, new org.apache.thrift.meta_data.FieldMetaData("failedCompares", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TItemReference.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TResponse.class, metaDataMap);
  }

  public TResponse() {
  }

  public TResponse(
    boolean success,
    java.util.List<TItem> readItems,
    java.util.List<TItemReference> failedCompares)
  {
    this();
    this.success = success;
    setSuccessIsSet(true);
    this.readItems = readItems;
    this.failedCompares = failedCompares;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TResponse(TResponse other) {
    __isset_bitfield = other.__isset_bitfield;
    this.success = other.success;
    if (other.isSetReadItems()) {
      java.util.List<TItem> __this__readItems = new java.util.ArrayList<TItem>(other.readItems.size());
      for (TItem other_element : other.readItems) {
        __this__readItems.add(new TItem(other_element));
      }
      this.readItems = __this__readItems;
    }
    if (other.isSetFailedCompares()) {
      java.util.List<TItemReference> __this__failedCompares = new java.util.ArrayList<TItemReference>(other.failedCompares.size());
      for (TItemReference other_element : other.failedCompares) {
        __this__failedCompares.add(new TItemReference(other_element));
      }
      this.failedCompares = __this__failedCompares;
    }
  }

  @Override
  public TResponse deepCopy() {
    return new TResponse(this);
  }

  @Override
  public void clear() {
    setSuccessIsSet(false);
    this.success = false;
    this.readItems = null;
    this.failedCompares = null;
  }

  public boolean isSuccess() {
    return this.success;
  }

  public TResponse setSuccess(boolean success) {
    this.success = success;
    setSuccessIsSet(true);
    return this;
  }

  public void unsetSuccess() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SUCCESS_ISSET_ID);
  }

  /** Returns true if field success is set (has been assigned a value) and false otherwise */
  public boolean isSetSuccess() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SUCCESS_ISSET_ID);
  }

  public void setSuccessIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SUCCESS_ISSET_ID, value);
  }

  public int getReadItemsSize() {
    return (this.readItems == null) ? 0 : this.readItems.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<TItem> getReadItemsIterator() {
    return (this.readItems == null) ? null : this.readItems.iterator();
  }

  public void addToReadItems(TItem elem) {
    if (this.readItems == null) {
      this.readItems = new java.util.ArrayList<TItem>();
    }
    this.readItems.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<TItem> getReadItems() {
    return this.readItems;
  }

  public TResponse setReadItems(@org.apache.thrift.annotation.Nullable java.util.List<TItem> readItems) {
    this.readItems = readItems;
    return this;
  }

  public void unsetReadItems() {
    this.readItems = null;
  }

  /** Returns true if field readItems is set (has been assigned a value) and false otherwise */
  public boolean isSetReadItems() {
    return this.readItems != null;
  }

  public void setReadItemsIsSet(boolean value) {
    if (!value) {
      this.readItems = null;
    }
  }

  public int getFailedComparesSize() {
    return (this.failedCompares == null) ? 0 : this.failedCompares.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<TItemReference> getFailedComparesIterator() {
    return (this.failedCompares == null) ? null : this.failedCompares.iterator();
  }

  public void addToFailedCompares(TItemReference elem) {
    if (this.failedCompares == null) {
      this.failedCompares = new java.util.ArrayList<TItemReference>();
    }
    this.failedCompares.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<TItemReference> getFailedCompares() {
    return this.failedCompares;
  }

  public TResponse setFailedCompares(@org.apache.thrift.annotation.Nullable java.util.List<TItemReference> failedCompares) {
    this.failedCompares = failedCompares;
    return this;
  }

  public void unsetFailedCompares() {
    this.failedCompares = null;
  }

  /** Returns true if field failedCompares is set (has been assigned a value) and false otherwise */
  public boolean isSetFailedCompares() {
    return this.failedCompares != null;
  }

  public void setFailedComparesIsSet(boolean value) {
    if (!value) {
      this.failedCompares = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case SUCCESS:
      if (value == null) {
        unsetSuccess();
      } else {
        setSuccess((java.lang.Boolean)value);
      }
      break;

    case READ_ITEMS:
      if (value == null) {
        unsetReadItems();
      } else {
        setReadItems((java.util.List<TItem>)value);
      }
      break;

    case FAILED_COMPARES:
      if (value == null) {
        unsetFailedCompares();
      } else {
        setFailedCompares((java.util.List<TItemReference>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case SUCCESS:
      return isSuccess();

    case READ_ITEMS:
      return getReadItems();

    case FAILED_COMPARES:
      return getFailedCompares();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case SUCCESS:
      return isSetSuccess();
    case READ_ITEMS:
      return isSetReadItems();
    case FAILED_COMPARES:
      return isSetFailedCompares();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof TResponse)
      return this.equals((TResponse)that);
    return false;
  }

  public boolean equals(TResponse that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_success = true;
    boolean that_present_success = true;
    if (this_present_success || that_present_success) {
      if (!(this_present_success && that_present_success))
        return false;
      if (this.success != that.success)
        return false;
    }

    boolean this_present_readItems = true && this.isSetReadItems();
    boolean that_present_readItems = true && that.isSetReadItems();
    if (this_present_readItems || that_present_readItems) {
      if (!(this_present_readItems && that_present_readItems))
        return false;
      if (!this.readItems.equals(that.readItems))
        return false;
    }

    boolean this_present_failedCompares = true && this.isSetFailedCompares();
    boolean that_present_failedCompares = true && that.isSetFailedCompares();
    if (this_present_failedCompares || that_present_failedCompares) {
      if (!(this_present_failedCompares && that_present_failedCompares))
        return false;
      if (!this.failedCompares.equals(that.failedCompares))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((success) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetReadItems()) ? 131071 : 524287);
    if (isSetReadItems())
      hashCode = hashCode * 8191 + readItems.hashCode();

    hashCode = hashCode * 8191 + ((isSetFailedCompares()) ? 131071 : 524287);
    if (isSetFailedCompares())
      hashCode = hashCode * 8191 + failedCompares.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetSuccess(), other.isSetSuccess());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSuccess()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetReadItems(), other.isSetReadItems());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReadItems()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.readItems, other.readItems);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetFailedCompares(), other.isSetFailedCompares());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFailedCompares()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.failedCompares, other.failedCompares);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TResponse(");
    boolean first = true;

    sb.append("success:");
    sb.append(this.success);
    first = false;
    if (!first) sb.append(", ");
    sb.append("readItems:");
    if (this.readItems == null) {
      sb.append("null");
    } else {
      sb.append(this.readItems);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("failedCompares:");
    if (this.failedCompares == null) {
      sb.append("null");
    } else {
      sb.append(this.failedCompares);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TResponseStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TResponseStandardScheme getScheme() {
      return new TResponseStandardScheme();
    }
  }

  private static class TResponseStandardScheme extends org.apache.thrift.scheme.StandardScheme<TResponse> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, TResponse struct) throws org.apache.thrift.TException {
      iprot.incrementRecursionDepth();
      try {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
                struct.success = iprot.readBool();
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // READ_ITEMS
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list40 = iprot.readListBegin();
                  struct.readItems = new java.util.ArrayList<TItem>(_list40.size);
                  @org.apache.thrift.annotation.Nullable TItem _elem41;
                  for (int _i42 = 0; _i42 < _list40.size; ++_i42)
                  {
                    _elem41 = new TItem();
                    _elem41.read(iprot);
                    struct.readItems.add(_elem41);
                  }
                  iprot.readListEnd();
                }
                struct.setReadItemsIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 3: // FAILED_COMPARES
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list43 = iprot.readListBegin();
                  struct.failedCompares = new java.util.ArrayList<TItemReference>(_list43.size);
                  @org.apache.thrift.annotation.Nullable TItemReference _elem44;
                  for (int _i45 = 0; _i45 < _list43.size; ++_i45)
                  {
                    _elem44 = new TItemReference();
                    _elem44.read(iprot);
                    struct.failedCompares.add(_elem44);
                  }
                  iprot.readListEnd();
                }
                struct.setFailedComparesIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      } finally {
        iprot.decrementRecursionDepth();
      }
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, TResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
      oprot.writeBool(struct.success);
      oprot.writeFieldEnd();
      if (struct.readItems != null) {
        oprot.writeFieldBegin(READ_ITEMS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.readItems.size()));
          for (TItem _iter46 : struct.readItems)
          {
            _iter46.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.failedCompares != null) {
        oprot.writeFieldBegin(FAILED_COMPARES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.failedCompares.size()));
          for (TItemReference _iter47 : struct.failedCompares)
          {
            _iter47.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TResponseTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TResponseTupleScheme getScheme() {
      return new TResponseTupleScheme();
    }
  }

  private static class TResponseTupleScheme extends org.apache.thrift.scheme.TupleScheme<TResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetSuccess()) {
        optionals.set(0);
      }
      if (struct.isSetReadItems()) {
        optionals.set(1);
      }
      if (struct.isSetFailedCompares()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetSuccess()) {
        oprot.writeBool(struct.success);
      }
      if (struct.isSetReadItems()) {
        {
          oprot.writeI32(struct.readItems.size());
          for (TItem _iter48 : struct.readItems)
          {
            _iter48.write(oprot);
          }
        }
      }
      if (struct.isSetFailedCompares()) {
        {
          oprot.writeI32(struct.failedCompares.size());
          for (TItemReference _iter49 : struct.failedCompares)
          {
            _iter49.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TResponse struct) throws org.apache.thrift.TException {
      prot.incrementRecursionDepth();
      try {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(3);
        if (incoming.get(0)) {
          struct.success = iprot.readBool();
          struct.setSuccessIsSet(true);
        }
        if (incoming.get(1)) {
          {
            org.apache.thrift.protocol.TList _list50 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
            struct.readItems = new java.util.ArrayList<TItem>(_list50.size);
            @org.apache.thrift.annotation.Nullable TItem _elem51;
            for (int _i52 = 0; _i52 < _list50.size; ++_i52)
            {
              _elem51 = new TItem();
              _elem51.read(iprot);
              struct.readItems.add(_elem51);
            }
          }
          struct.setReadItemsIsSet(true);
        }
        if (incoming.get(2)) {
          {
            org.apache.thrift.protocol.TList _list53 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
            struct.failedCompares = new java.util.ArrayList<TItemReference>(_list53.size);
            @org.apache.thrift.annotation.Nullable TItemReference _elem54;
            for (int _i55 = 0; _i55 < _list53.size; ++_i55)
            {
              _elem54 = new TItemReference();
              _elem54.read(iprot);
              struct.failedCompares.add(_elem54);
            }
          }
          struct.setFailedComparesIsSet(true);
        }
      } finally {
        prot.decrementRecursionDepth();
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

