/**
 * Autogenerated by Thrift Compiler (0.23.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.people.mreutegg.jsinfonia.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.23.0)", date = "2026-05-15")
public enum TVote implements org.apache.thrift.TEnum {
  OK(0),
  BAD_LOCK(1),
  BAD_FORCED(2),
  BAD_CMP(3),
  BAD_IO(4);

  private final int value;

  private TVote(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static TVote findByValue(int value) { 
    switch (value) {
      case 0:
        return OK;
      case 1:
        return BAD_LOCK;
      case 2:
        return BAD_FORCED;
      case 3:
        return BAD_CMP;
      case 4:
        return BAD_IO;
      default:
        return null;
    }
  }
}
